package agent

import (
	"bytes"
	"context"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// generateReportPDF creates a PDF report from query results and saves it to storage.
// Returns the public download URL.
func (e *AgentEngine) generateReportPDF(ctx context.Context, title string, columns []string, rows [][]interface{}) (string, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 20)
	pdf.AddPage()

	// Title
	pdf.SetFont("Helvetica", "B", 16)
	pdf.CellFormat(190, 10, title, "", 1, "C", false, 0, "")
	pdf.Ln(4)

	// Generation time
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(128, 128, 128)
	pdf.CellFormat(190, 6, "生成时间: "+time.Now().Format("2006-01-02 15:04:05"), "", 1, "C", false, 0, "")
	pdf.Ln(6)

	if len(columns) == 0 || len(rows) == 0 {
		pdf.SetFont("Helvetica", "", 12)
		pdf.SetTextColor(0, 0, 0)
		pdf.CellFormat(190, 10, "没有数据", "", 1, "C", false, 0, "")
	} else {
		// Table header
		colWidth := 190.0 / float64(len(columns))
		if colWidth > 50 {
			colWidth = 50
		}
		pdf.SetFont("Helvetica", "B", 9)
		pdf.SetFillColor(60, 60, 180)
		pdf.SetTextColor(255, 255, 255)
		for _, col := range columns {
			pdf.CellFormat(colWidth, 8, col, "1", 0, "C", true, 0, "")
		}
		pdf.Ln(-1)

		// Table rows
		pdf.SetFont("Helvetica", "", 8)
		pdf.SetTextColor(0, 0, 0)
		fill := false
		for _, row := range rows {
			if fill {
				pdf.SetFillColor(245, 245, 250)
			} else {
				pdf.SetFillColor(255, 255, 255)
			}
			for _, cell := range row {
				text := fmt.Sprintf("%v", cell)
				if len(text) > 40 {
					text = text[:37] + "..."
				}
				pdf.CellFormat(colWidth, 7, text, "1", 0, "L", true, 0, "")
			}
			pdf.Ln(-1)
			fill = !fill
		}
	}

	// Footer
	pdf.SetY(-25)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(128, 128, 128)
	pdf.CellFormat(0, 10, fmt.Sprintf("Generated by OpenTether | %d rows", len(rows)), "", 0, "C", false, 0, "")

	// Output to buffer
	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return "", fmt.Errorf("PDF 生成失败: %w", err)
	}

	// Save to storage
	fileName := fmt.Sprintf("reports/%s_%s.pdf", sanitizeFilename(title), time.Now().Format("20060102_150405"))
	url, err := e.store.Save(ctx, fileName, buf.Bytes(), "application/pdf")
	if err != nil {
		return "", fmt.Errorf("PDF 保存失败: %w", err)
	}

	return url, nil
}

func sanitizeFilename(name string) string {
	result := make([]byte, 0, len(name))
	for _, c := range []byte(name) {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_' || c == '-' {
			result = append(result, c)
		} else if c == ' ' {
			result = append(result, '_')
		}
	}
	if len(result) == 0 {
		return "report"
	}
	return string(result)
}
