package service

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/ast"
	"github.com/yuin/goldmark/parser"
)

// MarkdownPDFService Markdown 转 PDF 服务
type MarkdownPDFService struct {
	pdf      *gofpdf.Fpdf
	fontSize float64
	indent   float64
}

func NewMarkdownPDFService() *MarkdownPDFService {
	return &MarkdownPDFService{}
}

// Convert Markdown 转 PDF
func (s *MarkdownPDFService) Convert(markdown string) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.AddPage()

	s.pdf = pdf
	s.fontSize = 11
	s.indent = 0

	// 解析 Markdown - 使用简单配置兼容 goldmark v1.7.1
	md := goldmark.New(
		goldmark.WithParser(
			parser.NewParser(),
		),
	)

	// 渲染 AST
	doc := md.Parser().Parse(nil)
	s.renderNode(doc)

	// 输出到内存 (gofpdf v1.16.2 只返回 error)
	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

// renderNode 渲染 AST 节点
func (s *MarkdownPDFService) renderNode(node ast.Node) {
	switch n := node.(type) {
	case *ast.Document:
		for child := node.FirstChild(); child != nil; child = child.NextSibling() {
			s.renderNode(child)
		}

	case *ast.Heading:
		level := n.Level
		fontSizes := map[int]float64{
			1: 20,
			2: 16,
			3: 14,
			4: 12,
			5: 11,
			6: 10,
		}
		s.fontSize = fontSizes[level]
		s.pdf.SetFont("helvetica", "B", s.fontSize)

		// 处理标题文本
		var text string
		for child := n.FirstChild(); child != nil; child = child.NextSibling() {
			text += s.extractText(child)
		}

		s.pdf.Ln(5)
		s.pdf.Cell(0, s.fontSize*1.5, text)
		s.pdf.Ln(s.fontSize * 0.8)
		s.fontSize = 11
		s.pdf.SetFont("helvetica", "", s.fontSize)

	case *ast.Paragraph:
		text := s.extractText(n)
		if text != "" {
			s.pdf.MultiCell(0, s.fontSize*1.5, text, "", "", false)
			s.pdf.Ln(3)
		}

	case *ast.List:
		s.renderList(n)

	case *ast.CodeBlock:
		// 代码块 - goldmark v1.7.1 直接获取文本内容
		var code string
		for child := n.FirstChild(); child != nil; child = child.NextSibling() {
			code += s.extractText(child)
		}

		s.pdf.SetFont("courier", "", 9)
		s.pdf.SetFillColor(245, 245, 245)

		lines := strings.Split(code, "\n")
		lineHeight := 5.0

		for _, line := range lines {
			_, y := s.pdf.GetXY()
			if y > 260 {
				s.pdf.AddPage()
				s.pdf.SetXY(20, 20)
			}
			s.pdf.Cell(170, lineHeight, line)
			s.pdf.Ln(lineHeight)
		}
		s.pdf.SetFont("helvetica", "", s.fontSize)
		s.pdf.Ln(3)

	case *ast.Blockquote:
		// 引用块
		s.pdf.SetTextColor(100, 100, 100)
		oldFontSize := s.fontSize
		s.fontSize = 10

		var text string
		for child := n.FirstChild(); child != nil; child = child.NextSibling() {
			text += s.extractText(child)
		}

		s.pdf.SetFont("helvetica", "I", s.fontSize)
		s.pdf.MultiCell(0, s.fontSize*1.4, text, "", "", false)
		s.pdf.Ln(3)

		s.fontSize = oldFontSize
		s.pdf.SetFont("helvetica", "", s.fontSize)
		s.pdf.SetTextColor(0, 0, 0)

	case *ast.ThematicBreak:
		// goldmark v1.7.1 使用 ThematicBreak 表示水平分隔线
		s.pdf.Ln(5)
		s.pdf.Line(20, s.pdf.GetY(), 190, s.pdf.GetY())
		s.pdf.Ln(5)
	}
}

// renderList 渲染列表
func (s *MarkdownPDFService) renderList(n *ast.List) {
	marker := n.Marker
	isOrdered := marker >= '1' && marker <= '9'

	// 保存当前位置
	startX, startY := s.pdf.GetXY()

	itemIdx := 1
	for child := n.FirstChild(); child != nil; child = child.NextSibling() {
		if listItem, ok := child.(*ast.ListItem); ok {
			// 绘制项目符号
			if isOrdered {
				s.pdf.CellFormat(10, s.fontSize*1.5, fmt.Sprintf("%d.", itemIdx), "", 0, "R", false, 0, "")
			} else {
				s.pdf.CellFormat(10, s.fontSize*1.5, "•", "", 0, "C", false, 0, "")
			}

			// 处理列表项内容
			var text string
			for c := listItem.FirstChild(); c != nil; c = c.NextSibling() {
				text += s.extractText(c)
			}

			// 设置缩进
			s.pdf.SetXY(startX+15, startY)
			s.pdf.MultiCell(0, s.fontSize*1.5, text, "", "", false)

			// 更新起始位置
			_, startY = s.pdf.GetXY()
			s.pdf.SetXY(startX, startY)

			itemIdx++
		}
	}
}

// extractText 提取节点文本 - 使用递归方式兼容 goldmark v1.7.1
func (s *MarkdownPDFService) extractText(node ast.Node) string {
	// 递归处理子节点获取文本
	var text string
	for child := node.FirstChild(); child != nil; child = child.NextSibling() {
		text += s.extractText(child)
	}
	return text
}

// ConvertWithStyles 带样式的转换
func (s *MarkdownPDFService) ConvertWithStyles(markdown string, title string) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.AddPage()

	s.pdf = pdf
	s.fontSize = 11
	s.indent = 0

	// 如果有标题，添加标题页
	if title != "" {
		pdf.AddPage()
		pdf.SetFont("helvetica", "B", 24)
		pdf.Cell(0, 30, title)
		pdf.Ln(15)
		pdf.SetFont("helvetica", "", 12)
		pdf.Cell(0, 8, "Generated by OpenTether")
		pdf.Ln(5)
		pdf.SetFont("helvetica", "I", 10)
		pdf.SetTextColor(128, 128, 128)
		pdf.Cell(0, 5, fmt.Sprintf("Generated at %s", "2024-01-01"))
		pdf.Ln(20)

		// 添加目录占位符
		pdf.SetTextColor(0, 0, 0)
		pdf.SetFont("helvetica", "B", 14)
		pdf.Cell(0, 8, "Table of Contents")
		pdf.Ln(10)
		pdf.SetFont("helvetica", "", 11)
		pdf.Cell(0, 6, "1. Introduction")
		pdf.Cell(0, 6, "2. Content")

		// 新页面开始正文
		pdf.AddPage()
	}

	// 解析 Markdown
	md := goldmark.New()
	doc := md.Parser().Parse(nil)
	s.renderNode(doc)

	// 输出到内存
	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

// ConvertWithTemplate 带模板的转换
func (s *MarkdownPDFService) ConvertWithTemplate(markdown string, tmpl *PDFTemplate) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(tmpl.MarginLeft, tmpl.MarginTop, tmpl.MarginRight)
	pdf.AddPage()

	s.pdf = pdf
	s.fontSize = tmpl.BaseFontSize

	// 如果有标题，添加标题页
	if tmpl.Title != "" {
		pdf.AddPage()
		pdf.SetFont("helvetica", "B", tmpl.TitleFontSize)
		pdf.Cell(0, 30, tmpl.Title)
		pdf.Ln(15)

		pdf.SetFont("helvetica", "", 12)
		if tmpl.Author != "" {
			pdf.Cell(0, 8, "Author: "+tmpl.Author)
			pdf.Ln(5)
		}
		pdf.SetFont("helvetica", "I", 10)
		pdf.SetTextColor(128, 128, 128)
		pdf.Cell(0, 5, fmt.Sprintf("Generated at %s", time.Now().Format("2006-01-02 15:04:05")))
		pdf.Ln(20)
		pdf.AddPage()
	}

	s.fontSize = tmpl.BaseFontSize
	pdf.SetFont("helvetica", "", s.fontSize)

	// 解析 Markdown
	md := goldmark.New()
	doc := md.Parser().Parse(nil)
	s.renderNode(doc)

	// 如果有水印
	if tmpl.Watermark != "" {
		// 在每一页添加水印
		pdf.SetAlpha(0.1, "Normal")
		pdf.SetFont("helvetica", "B", 60)
		pdf.SetTextColor(200, 200, 200)
		pdf.Text(50, 150, tmpl.Watermark)
		pdf.SetAlpha(1.0, "Normal")
		pdf.SetTextColor(0, 0, 0)
	}

	// 输出到内存
	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}


// PDFTemplate PDF 模板
type PDFTemplate struct {
	Title           string
	Author          string
	Watermark       string
	MarginLeft      float64
	MarginRight     float64
	MarginTop       float64
	MarginBottom    float64
	TitleFontSize   float64
	BaseFontSize    float64
}

// DefaultTemplate 默认模板
func DefaultTemplate() *PDFTemplate {
	return &PDFTemplate{
		MarginLeft:   20,
		MarginRight:  20,
		MarginTop:    20,
		MarginBottom: 20,
		TitleFontSize: 24,
		BaseFontSize:  11,
	}
}
