package service

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// PDFService PDF 生成服务
type PDFService struct{}

func NewPDFService() *PDFService {
	return &PDFService{}
}

// ReportData 报表数据
type ReportData struct {
	Title       string
	Subtitle    string
	Columns     []string
	Rows        [][]interface{}
	Summary     string
	GeneratedAt time.Time
	Footer      string
}

// GenerateReport 生成 PDF 报表
func (s *PDFService) GenerateReport(data *ReportData) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(15, 15, 15)
	pdf.AddPage()

	// 设置字体
	pdf.SetFont("helvetica", "", 12)

	// 标题
	pdf.SetFont("helvetica", "B", 18)
	pdf.Cell(0, 12, data.Title)
	pdf.Ln(8)

	// 副标题
	if data.Subtitle != "" {
		pdf.SetFont("helvetica", "", 11)
		pdf.SetTextColor(100, 100, 100)
		pdf.Cell(0, 6, data.Subtitle)
		pdf.Ln(8)
	}

	pdf.SetTextColor(0, 0, 0)

	// 表格
	if len(data.Columns) > 0 && len(data.Rows) > 0 {
		pdf.Ln(5)
		s.addTable(pdf, data.Columns, data.Rows)
	}

	// 摘要
	if data.Summary != "" {
		pdf.Ln(10)
		pdf.SetFont("helvetica", "B", 11)
		pdf.Cell(0, 6, "摘要")
		pdf.Ln(6)
		pdf.SetFont("helvetica", "", 10)
		pdf.MultiCell(0, 5, data.Summary, "", "", false)
	}

	// 页脚
	pdf.Ln(15)
	pdf.SetFont("helvetica", "I", 8)
	pdf.SetTextColor(128, 128, 128)

	footer := data.Footer
	if footer == "" {
		footer = fmt.Sprintf("Generated by OpenTether at %s", data.GeneratedAt.Format("2006-01-02 15:04:05"))
	}
	pdf.Cell(0, 4, footer)

	// 输出到内存
	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

// addTable 添加表格
func (s *PDFService) addTable(pdf *gofpdf.Fpdf, headers []string, rows [][]interface{}) {
	// 计算列宽
	pageWidth, _ := pdf.GetPageSize()
	_, right, _, left := pdf.GetMargins()
	usableWidth := pageWidth - left - right

	colCount := len(headers)
	if colCount == 0 {
		return
	}

	colWidth := usableWidth / float64(colCount)

	// 表头
	pdf.SetFont("helvetica", "B", 9)
	pdf.SetFillColor(240, 240, 240)

	for i, header := range headers {
		x, y := pdf.GetXY()
		pdf.CellFormat(colWidth, 7, header, "1", 0, "C", true, 0, "")
		if i == colCount-1 {
			pdf.Ln(7)
		} else {
			pdf.SetXY(x+colWidth, y)
		}
	}

	// 表格内容
	pdf.SetFont("helvetica", "", 9)
	pdf.SetFillColor(255, 255, 255)

	for rowIdx, row := range rows {
		if rowIdx > 50 {
			// 限制最多显示 50 行
			pdf.Ln(5)
			pdf.SetFont("helvetica", "I", 9)
			pdf.Cell(0, 5, fmt.Sprintf("... 共 %d 条记录，仅显示前 50 条", len(rows)))
			break
		}

		// 交替行颜色
		if rowIdx%2 == 0 {
			pdf.SetFillColor(250, 250, 250)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}

		for colIdx, cell := range row {
			cellStr := s.formatCell(cell)
			x, y := pdf.GetXY()
			pdf.CellFormat(colWidth, 6, cellStr, "1", 0, "L", true, 0, "")
			if colIdx == colCount-1 {
				pdf.Ln(6)
			} else {
				pdf.SetXY(x+colWidth, y)
			}
		}
	}
}

// formatCell 格式化单元格内容
func (s *PDFService) formatCell(cell interface{}) string {
	if cell == nil {
		return ""
	}
	str := fmt.Sprintf("%v", cell)
	// 移除换行符
	str = strings.ReplaceAll(str, "\n", " ")
	str = strings.ReplaceAll(str, "\r", "")
	// 截断过长的内容
	if len(str) > 50 {
		str = str[:47] + "..."
	}
	return str
}

// GenerateEmployeeReport 生成员工报表
func (s *PDFService) GenerateEmployeeReport(title string, columns []string, rows [][]interface{}) ([]byte, error) {
	reportData := &ReportData{
		Title:       title,
		Subtitle:    "员工数据报表",
		Columns:     columns,
		Rows:        rows,
		Summary:     fmt.Sprintf("共 %d 条员工记录", len(rows)),
		GeneratedAt: time.Now(),
		Footer:      "OpenTether Enterprise AI Agent System",
	}

	return s.GenerateReport(reportData)
}

// GenerateQueryReport 生成查询结果报表
func (s *PDFService) GenerateQueryReport(query string, columns []string, rows [][]interface{}) ([]byte, error) {
	reportData := &ReportData{
		Title:       "查询结果报表",
		Subtitle:    "SQL: " + query,
		Columns:     columns,
		Rows:        rows,
		Summary:     fmt.Sprintf("查询返回 %d 条记录，执行时间: %s", len(rows), time.Now().Format("15:04:05")),
		GeneratedAt: time.Now(),
		Footer:      "OpenTether - Data Query Report",
	}

	return s.GenerateReport(reportData)
}

// GenerateSummaryReport 生成汇总报表
func (s *PDFService) GenerateSummaryReport(title, content string, stats map[string]interface{}) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.AddPage()

	// 标题
	pdf.SetFont("helvetica", "B", 20)
	pdf.Cell(0, 15, title)
	pdf.Ln(12)

	// 生成时间
	pdf.SetFont("helvetica", "", 10)
	pdf.SetTextColor(128, 128, 128)
	pdf.Cell(0, 5, fmt.Sprintf("生成时间: %s", time.Now().Format("2006-01-02 15:04:05")))
	pdf.Ln(10)

	pdf.SetTextColor(0, 0, 0)

	// 内容
	pdf.SetFont("helvetica", "", 11)
	pdf.MultiCell(0, 6, content, "", "", false)
	pdf.Ln(10)

	// 统计信息
	if len(stats) > 0 {
		pdf.SetFont("helvetica", "B", 12)
		pdf.Cell(0, 8, "统计信息")
		pdf.Ln(8)

		pdf.SetFont("helvetica", "", 10)
		for key, value := range stats {
			pdf.Cell(60, 6, fmt.Sprintf("%s:", key))
			pdf.Cell(0, 6, fmt.Sprintf("%v", value))
		}
	}

	// 页脚
	pdf.Ln(15)
	pdf.SetFont("helvetica", "I", 8)
	pdf.SetTextColor(128, 128, 128)
	pdf.Cell(0, 4, "Generated by OpenTether Enterprise AI Agent System")

	// 输出
	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
